### ISSUE TITLE
allow script tag

### ISSUE THREAD

**Issue by mm580486** [rails/rails-html-sanitizer#140]
Hi in your DC i cant find anything about javascript tag or etc like that i used grape and your gem but script tag remove after render
`            full_sanitizer.sanitize(ERB.new(raw).result(binding),tags: %w( form  comment blockquote ))`

**Comment by flavorjones** [comment]
Hi, by default `script` tags are removed by this gem because the goal is to sanitize untrusted HTML.

You can override the set of disallowed tags if you wish, but allowing `script` tags to remain in untrusted HTML is not safe, you shouldn't do it, and this gem may not solve the problem you think you're solving.

If you want to ask some more specific questions I'd be happy to try to answer, but in the meantime I'm going to close this issue.
